### ISSUE TITLE
Esp8266 pin

### ISSUE THREAD

**Issue by brkysnol** [HomeKidd/ESP8266-HomeKit-Paradox-Alarm-System#2]
which pins go to the paradox panel ?

**Comment by HomeKidd** [comment]
Hi!

Currently none of them. Please read issue #1  and the [readme](https://github.com/HomeKidd/ESP8266-HomeKit-Paradox-Alarm-System#still-in-development-currently-its-just-an-empty-homekit-security-system-accessory-and-not-controlling-anything)
